DROP TABLE IF EXISTS NewMovie;

CREATE TABLE IF NOT EXISTS NewMovie(
id SERIAL PRIMARY KEY,
release_date DATE,
title VARCHAR(1000),
poster_path VARCHAR(1000),
overview VARCHAR(10000),
my_comment VARCHAR(1000)
);